name: Deploy .nojekyll

on:
  push:
    branches:
      - main

jobs:
  add-nojekyll:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit and push .nojekyll file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add release/wwwroot/.nojekyll
        git commit -m 'Add .nojekyll file'
        git push
