name: gh-pages push action
  
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        
    - name: Copy Branch to Destination Repository
      run: |
        git config --global user.email 'kuht07@mail.ru'
        git config --global user.name 'VitalKz'
        git push https://VitalKz:${{ secrets.PAT }}@github.com/VitalKz/SatelShop.github.io.git gh-pages:main
      env:
        PAT_TOKEN: ${{ secrets.PAT }}
