name: gh-pages push action
  
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write # We generate static HTML, JS, CSS so we need write access to the repo
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
        
    - name: Copy Branch to Destination Repository
      run: |
        git config --global user.email 'kuht07@mail.ru'
        git config --global user.name 'VitalKz'
        git push https://VitalKz:${{ secrets.ACTIONS_KEY }}@github.com/VitalKz/SatelShop.github.io.git gh-pages:main
      env:
        ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
