name: gh-pages push action
  
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Copy Branch to Destination Repository
      run: |
        ls -l ~/.ssh
        git config --global user.email 'kuht07@mail.ru'
        git config --global user.name 'VitalKz'
        git push git@github.com:VitalKz/SatelShop.github.io.git gh-pages:main
