name: gh-pages push action
  
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0
    
    - name: Copy Branch to Destination Repository
      run: |
        git config --global user.email 'kuht07@mail.ru'
        git config --global user.name 'VitalKz'

        # Fetch the latest changes from the gh-pages branch
        git fetch origin gh-pages

        # Reset the main branch to match the latest commit of gh-pages
        git checkout main
        git reset --hard origin/gh-pages

        # Add, commit, and push the changes to the main branch
        git add .
        git commit -m "New build from gh-pages"
        git push https://VitalKz:${{ secrets.PAT }}@github.com/VitalKz/SatelShop.github.io.git main    
      env:
        PAT_TOKEN: ${{ secrets.PAT }}
